"use client";

import { useState } from "react";
import { EmptyState, Metric, StatusPill, WorkspacePanel } from "@/components/user-workspace/WorkspaceUI";
import type { UserWorkspaceState } from "@/components/user-workspace/useUserWorkspace";
import type { WorkspaceView } from "@/components/user-workspace/UserWorkspaceShell";

export function UserResources({ view, state, onView }: { view: Exclude<WorkspaceView, "home" | "assistant" | "coder">; state: UserWorkspaceState; onView: (view: WorkspaceView) => void }) {
  if (view === "templates") return <Templates state={state} onUse={() => onView("assistant")} />;
  if (view === "work") return <MyWork state={state} />;
  if (view === "documents") return <Documents state={state} onAssistant={() => onView("assistant")} />;
  if (view === "knowledge") return <Knowledge state={state} />;
  if (view === "approvals") return <Approvals state={state} />;
  if (view === "usage") return <Usage state={state} />;
  if (view === "notifications") return <Notifications state={state} />;
  if (view === "settings") return <Settings state={state} />;
  if (view === "models") return <Models state={state} />;
  if (view === "audit") return <Audit state={state} />;
  if (view === "shared") return <Section title="Shared with Me" description="Conversations and artifacts shared with your account"><EmptyState title="Nothing has been shared with you." description="Shared conversations, documents, presentations, and diagrams will appear here." /></Section>;
  const artifactType = view === "presentations" ? "PowerPoint" : view === "reports" ? "Report" : "diagram";
  return <Artifacts state={state} title={view[0].toUpperCase() + view.slice(1)} type={artifactType} />;
}

function Section({ title, description, children }: { title: string; description: string; children: React.ReactNode }) { return <div className="space-y-6"><div><p className="text-sm font-semibold uppercase tracking-[0.16em] text-blue-700">User Workspace</p><h1 className="mt-2 text-3xl font-semibold text-slate-950">{title}</h1><p className="mt-2 text-slate-600">{description}</p></div>{children}</div>; }

function Templates({ state, onUse }: { state: UserWorkspaceState; onUse: () => void }) {
  const [query, setQuery] = useState(""); const [category, setCategory] = useState("All");
  const categories = ["All", ...new Set(state.templates.map((item) => item.category))];
  const filtered = state.templates.filter((item) => (category === "All" || item.category === category) && `${item.name} ${item.description}`.toLowerCase().includes(query.toLowerCase()));
  return <Section title="Template Gallery" description="Approved starting points for repeatable business work"><div className="flex flex-col gap-3 rounded-xl border border-slate-200 bg-white p-4 sm:flex-row"><label className="flex-1"><span className="sr-only">Search templates</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search templates" className="h-11 w-full rounded-md border border-slate-300 px-3 text-sm" /></label><select aria-label="Template category" value={category} onChange={(event) => setCategory(event.target.value)} className="h-11 rounded-md border border-slate-300 px-3 text-sm">{categories.map((item) => <option key={item}>{item}</option>)}</select></div>{filtered.length ? <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{filtered.map((item) => <div key={item.id} className="rounded-xl border border-slate-200 bg-white p-5 text-slate-950"><div className="flex justify-between gap-3"><StatusPill>{item.category}</StatusPill><span className="text-amber-500">{item.favorite ? "★" : "☆"}</span></div><h2 className="mt-4 text-lg font-semibold">{item.name}</h2><p className="mt-2 text-sm leading-6 text-slate-600">{item.description}</p><dl className="mt-4 grid grid-cols-2 gap-2 text-xs text-slate-600"><div><dt>Persona</dt><dd className="mt-1 text-slate-700">{item.persona}</dd></div><div><dt>Output</dt><dd className="mt-1 text-slate-700">{item.outputFormat}</dd></div><div><dt>Version</dt><dd className="mt-1 text-slate-700">{item.version}</dd></div><div><dt>Approval</dt><dd className="mt-1 text-slate-700">{item.approvalStatus}</dd></div></dl><div className="mt-5 flex gap-2"><button type="button" onClick={onUse} className="rounded-md bg-blue-700 px-3 py-2 text-xs font-semibold text-white">Use template</button><button type="button" className="rounded-md border border-slate-300 px-3 py-2 text-xs text-slate-700">Preview</button></div></div>)}</div> : <EmptyState title="No matching templates." description="Change the search text or category filter." />}</Section>;
}

function MyWork({ state }: { state: UserWorkspaceState }) {
  const [status, setStatus] = useState("all"); const filtered = status === "all" ? state.tasks : state.tasks.filter((item) => item.status === status);
  return <Section title="My Work" description="Drafts, completed tasks, saved responses, generated artifacts, favorites, and archived work"><WorkspacePanel title="Work items" description="Filter by lifecycle status" action={<select aria-label="Filter work status" value={status} onChange={(event) => setStatus(event.target.value)} className="rounded-md border border-slate-300 bg-white px-3 py-2 text-xs"><option value="all">All statuses</option><option value="draft">Drafts</option><option value="completed">Completed</option><option value="awaiting-review">Awaiting review</option><option value="failed">Failed</option><option value="archived">Archived</option></select>}>{filtered.length ? <div className="overflow-x-auto"><table className="w-full min-w-[700px] text-left text-sm"><thead className="text-xs uppercase tracking-wider text-slate-500"><tr><th className="pb-3">Title</th><th className="pb-3">Task</th><th className="pb-3">Persona</th><th className="pb-3">Model</th><th className="pb-3">Status</th><th className="pb-3">Updated</th></tr></thead><tbody>{filtered.map((item) => <tr key={item.id} className="border-t border-slate-200"><td className="py-3 pr-3 text-slate-950">{item.title}</td><td className="py-3 pr-3 text-slate-600">{item.taskType}</td><td className="py-3 pr-3 text-slate-600">{item.persona}</td><td className="py-3 pr-3 text-slate-600">{item.model}</td><td className="py-3 pr-3"><StatusPill>{item.status}</StatusPill></td><td className="py-3 text-slate-500">{new Date(item.updatedAt).toLocaleDateString()}</td></tr>)}</tbody></table></div> : <EmptyState />}</WorkspacePanel></Section>;
}

function Documents({ state, onAssistant }: { state: UserWorkspaceState; onAssistant: () => void }) {
  const [sensitivity, setSensitivity] = useState("internal");
  return <Section title="Documents" description="Upload, index, analyse, compare, and add files to enterprise knowledge"><div className="rounded-xl border border-slate-200 bg-white p-5"><div className="flex flex-wrap items-center gap-3"><label className="cursor-pointer rounded-md bg-blue-700 px-4 py-2.5 text-sm font-semibold text-white hover:bg-blue-800"><input type="file" className="sr-only" accept=".pdf,.docx,.pptx,.xlsx,.csv,.txt,.png,.jpg,.jpeg,.webp,.json,.md" onChange={(event) => { const file = event.target.files?.[0]; if (file) void state.uploadFile(file, sensitivity); event.currentTarget.value = ""; }} />Upload document</label><select aria-label="Upload sensitivity" value={sensitivity} onChange={(event) => setSensitivity(event.target.value)} className="h-10 rounded-md border border-slate-300 px-3 text-sm"><option value="internal">Internal</option><option value="confidential">Confidential</option><option value="restricted">Restricted</option></select><span className="text-xs text-slate-500">PDF, Office, CSV, text, images, JSON, Markdown · 25 MB maximum</span></div></div><WorkspacePanel title="Files" description="Processing and indexing status">{state.files.length ? <div className="space-y-3">{state.files.map((file) => <div key={file.id} className="rounded-lg border border-slate-200 p-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><p className="font-medium text-slate-950">{file.name}</p><p className="mt-1 text-xs text-slate-500">{file.type} · {(file.size / 1024).toFixed(1)} KB · {file.owner} · {new Date(file.uploadedAt).toLocaleString()}</p></div><div className="flex gap-2"><StatusPill>{file.processingStatus}</StatusPill><StatusPill tone={file.indexingStatus === "Indexed" ? "green" : "slate"}>{file.indexingStatus}</StatusPill></div></div><div className="mt-3 flex flex-wrap gap-2">{["Preview", "Summarize", "Ask questions", "Compare", "Extract", "Re-index", "Add to knowledge"].map((action) => <button type="button" key={action} onClick={action === "Summarize" || action === "Ask questions" ? onAssistant : undefined} className="rounded border border-slate-300 px-2.5 py-1.5 text-xs text-slate-700">{action}</button>)}</div></div>)}</div> : <EmptyState title="No documents uploaded." description="Upload a supported file to summarize, compare, extract, or index it." />}</WorkspacePanel></Section>;
}

function Knowledge({ state }: { state: UserWorkspaceState }) { return <Section title="Enterprise Knowledge" description="Permission-aware sources available to PRISM retrieval"><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{state.knowledgeSources.map((source) => <div key={source.id} className="rounded-xl border border-slate-200 bg-white p-5 text-slate-950"><div className="flex justify-between gap-3"><h2 className="font-semibold">{source.name}</h2><StatusPill tone={source.status === "Connected" || source.status === "Available" ? "green" : source.status === "Indexing" ? "amber" : "slate"}>{source.status}</StatusPill></div><p className="mt-3 text-sm text-slate-600">{source.description}</p></div>)}</div></Section>; }

function Artifacts({ state, title, type }: { state: UserWorkspaceState; title: string; type: string }) { const items = state.artifacts.filter((item) => item.type.toLowerCase().includes(type.toLowerCase())); return <Section title={title} description={`Generated ${title.toLowerCase()}, versions, approvals, downloads, and sharing`}><WorkspacePanel title={title}>{items.length ? <div className="space-y-3">{items.map((item) => <div key={item.id} className="flex flex-col gap-3 rounded-lg border border-slate-200 p-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-medium text-slate-950">{item.name}</p><p className="mt-1 text-xs text-slate-500">{item.type} · v{item.version} · {item.owner}</p></div><div className="flex items-center gap-2"><StatusPill>{item.approvalStatus}</StatusPill><button type="button" className="text-xs text-blue-700">Download</button><button type="button" className="text-xs text-blue-700">Share</button><button type="button" className="text-xs text-blue-700">Revise</button></div></div>)}</div> : <EmptyState title={`No ${title.toLowerCase()} yet.`} description="Use the AI Assistant to create your first governed artifact." />}</WorkspacePanel></Section>; }

function Approvals({ state }: { state: UserWorkspaceState }) { return <Section title="Approvals" description="Submit, review, revise, approve, reject, and publish governed content"><WorkspacePanel title="Approval queue">{state.approvals.length ? <div className="space-y-3">{state.approvals.map((item) => <div key={item.id} className="flex flex-col gap-3 rounded-lg border border-slate-200 p-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-medium text-slate-950">{item.title}</p><p className="mt-1 text-xs text-slate-500">{item.owner} · {new Date(item.updatedAt).toLocaleString()}</p></div><div className="flex items-center gap-2"><StatusPill tone={item.status === "Approved" ? "green" : "amber"}>{item.status}</StatusPill>{state.profile?.permissions.canApprove ? <><button type="button" className="text-xs text-emerald-700">Approve</button><button type="button" className="text-xs text-red-700">Reject</button></> : null}</div></div>)}</div> : <EmptyState title="No approvals waiting." description="Submit a conversation or artifact when it is ready for review." />}</WorkspacePanel></Section>; }

function Usage({ state }: { state: UserWorkspaceState }) { return <Section title="Usage and Budget" description="Token consumption, estimated cost, model mix, and task activity"><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Input tokens" value={state.usage.inputTokens.toLocaleString()} detail="Current month" /><Metric label="Output tokens" value={state.usage.outputTokens.toLocaleString()} detail="Current month" /><Metric label="Estimated cost" value={`$${state.usage.estimatedCostUsd.toFixed(4)}`} detail={`$${state.usage.monthlyBudgetUsd.toFixed(2)} budget`} /><Metric label="Remaining budget" value={`$${state.usage.remainingBudgetUsd.toFixed(2)}`} detail="Current billing period" /></div><WorkspacePanel title="Usage profile"><div className="grid gap-4 md:grid-cols-2"><Info label="Most-used model" value={state.usage.mostUsedModel || "Not available"} /><Info label="Most-used task type" value={state.usage.mostUsedTaskType || "Not available"} /></div></WorkspacePanel></Section>; }

function Notifications({ state }: { state: UserWorkspaceState }) { return <Section title="Notifications" description="Tasks, artifacts, approvals, policy alerts, sharing, usage, and budget events"><WorkspacePanel title="Notification center">{state.notifications.length ? <div className="space-y-2">{state.notifications.map((item) => <div key={item.id} className={`rounded-lg border p-4 ${item.read ? "border-slate-200" : "border-blue-300/30 bg-blue-50"}`}><p className="text-sm font-medium text-slate-950">{item.title}</p><p className="mt-1 text-sm text-slate-600">{item.message}</p><p className="mt-2 text-xs text-slate-600">{new Date(item.createdAt).toLocaleString()}</p></div>)}</div> : <EmptyState title="You are all caught up." description="Task, approval, policy, sharing, and budget notifications will appear here." />}</WorkspacePanel></Section>; }

function Settings({ state }: { state: UserWorkspaceState }) { return <Section title="Settings" description="Personalize defaults, accessibility, notifications, language, and retention"><WorkspacePanel title="Workspace defaults"><div className="grid gap-4 md:grid-cols-2"><Setting label="Default persona"><select value={state.activePersonaId} onChange={(event) => state.setActivePersonaId(event.target.value)} className="field"><option value="">Select persona</option>{state.personas.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></Setting><Setting label="Default task type"><select value={state.activeTaskTypeId} onChange={(event) => state.setActiveTaskTypeId(event.target.value)} className="field">{state.promptTypes.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></Setting><Setting label="Output language"><select className="field" defaultValue="English"><option>English</option></select></Setting><Setting label="Default document format"><select className="field" defaultValue="Word"><option>Word</option><option>PDF</option><option>Markdown</option></select></Setting></div><p className="mt-5 text-xs text-slate-500">Settings persistence will activate when the profile settings backend is deployed.</p></WorkspacePanel></Section>; }

function Models({ state }: { state: UserWorkspaceState }) { return <Section title="Models" description="Authorized view of routing providers, tiers, context, and data policy"><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{state.models.map((model) => <div key={model.id} className="rounded-xl border border-slate-200 bg-white p-5 text-slate-950"><div className="flex justify-between"><h2 className="font-semibold">{model.label}</h2>{model.recommended ? <StatusPill tone="green">Recommended</StatusPill> : null}</div><p className="mt-3 text-sm text-slate-600">{model.provider || "PRISM"} · {model.tier}</p><p className="mt-2 text-xs text-slate-500">{model.contextWindow || "Context governed by route"}</p><p className="mt-2 text-xs text-slate-500">{model.dataPolicy}</p></div>)}</div></Section>; }

function Audit({ state }: { state: UserWorkspaceState }) { return <Section title="Audit" description="Authorized history of governed prompts, models, usage, and outcomes"><WorkspacePanel title="Execution history">{state.history.length ? <div className="space-y-2">{state.history.map((item) => <div key={item.id} className="grid gap-2 rounded-lg border border-slate-200 p-3 text-xs text-slate-600 md:grid-cols-5"><span>{new Date(item.timestamp).toLocaleString()}</span><span>{item.agent}</span><span>{item.model}</span><span>{item.inputTokens + item.outputTokens} tokens</span><span>{item.governanceStatus}</span></div>)}</div> : <EmptyState title="No audit events yet." description="Governed workspace executions will appear after the first request." />}</WorkspacePanel></Section>; }

function Setting({ label, children }: { label: string; children: React.ReactNode }) { return <label><span className="mb-2 block text-sm font-medium text-slate-700">{label}</span>{children}</label>; }
function Info({ label, value }: { label: string; value: string }) { return <div className="rounded-lg border border-slate-200 p-4"><p className="text-xs text-slate-500">{label}</p><p className="mt-2 font-semibold text-slate-950">{value}</p></div>; }
